apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-utcv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fjhw-tenant/rhtap-demo-app/hacbs-test-project-utcv@sha256:f71a4430c684ec35566ef3fd4b5f8dfa89181ea55fff01688d6e2da6f03e736a
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
