apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-utcv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-utcv
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-utcv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-utcv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-utcv
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fjhw-tenant/rhtap-demo-app/hacbs-test-project-utcv@sha256:966de4a07ccffcb1e0bc1d3372bb344489617f3b63eed3ee9b9d864eb1e9bc01
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
